"""Input/output helpers for RogueLens results."""

from __future__ import annotations

import csv
from pathlib import Path

from .model import LightCurveResult, event_summary


def save_light_curve_csv(result: LightCurveResult, output_path: str | Path) -> Path:
    """Save a light curve as a CSV table."""

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["time_days", "separation_u", "magnification", "flux", "delta_magnitude"])
        for row in zip(
            result.time_days,
            result.separation_u,
            result.magnification,
            result.flux,
            result.delta_magnitude,
            strict=True,
        ):
            writer.writerow([f"{value:.10g}" for value in row])
    return output


def save_event_report(result: LightCurveResult, output_path: str | Path, *, title: str) -> Path:
    """Save a small human-readable Markdown report for one event."""

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    summary = event_summary(result)
    lines = [
        f"# {title}",
        "",
        "This report was generated by RogueLens. It summarizes one simulated point-lens microlensing event.",
        "",
        "## Input parameters",
        "",
    ]
    for key, value in result.parameters.items():
        lines.append(f"- `{key}`: {value:.6g}")
    lines += ["", "## Output summary", ""]
    for key, value in summary.items():
        lines.append(f"- `{key}`: {value:.6g}")
    lines += [
        "",
        "## Interpretation",
        "",
        "The curve rises when the lens-source angular separation becomes small and returns to the baseline after the alignment passes. The event is symmetric because the educational model assumes a single point lens moving in a straight line at constant transverse speed.",
    ]
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output
